### ISSUE TITLE
Make The Car Move

### ISSUE THREAD

**Issue by KalleHallden** [DIT112-V19/group-04#1]
As a maintainance mechanic I want to be able to make the car move so that I can verify that all motors are working as intended.

**Acceptance Criteria:**
All motors are rotating in the desired direction upon command.

**Comment by konradotto** [comment]
The motors are connected correctly to the pins specified in [usedpins.h!](https://github.com/DIT112-V19/group-04/blob/master/arduino/obstacleAvoidance/usedpins.h) and seem to be rotating normally.
