### ISSUE TITLE
Setup Bluetooth on car

### ISSUE THREAD

**Issue by KalleHallden** [DIT112-V19/group-04#2]
As a Passenger I want the Bluetooth hardware to be set up so that I can play my music on the car.

**Acceptance Criteria:**
Be able to connect to the Bluetooth chip from PCs and phones (IPhones excluded due to hardware incompatibility between the chip and IOs phones).

**Comment by konradotto** [comment]
The bluetooth device is visible from different devices and pairing devices to the car was successful (according to the devices' operation systems).
