### ISSUE TITLE
Server handling multiple cars and users

### ISSUE THREAD

**Issue by bartekspitza** [DIT112-V19/group-04#28]
As the CTO I want the system to be able to handle multiple users and cars

**Acceptance Criteria:**

The server should be able to receive requests from different clients, and storing their session information, such as location, destination etc.

**Comment by platisd** [comment]
Is the CTO really the stakeholder/user here? :grin:

**Comment by bartekspitza** [comment]
> Is the CTO really the stakeholder/user here?

Sure, why not?
