### ISSUE TITLE
Create Basic Interface app for steering

### ISSUE THREAD

**Issue by KalleHallden** [DIT112-V19/group-04#3]
As a maintainance mechanic I want an intuitive interface for steering the car so that I can move it when the self-driving capability is impeded by hardware issues.

**Acceptance Criteria:**
Be able to command movement on a 2D plane by simple button/mouse clicks.

**Comment by konradotto** [comment]
We still need to decide on the programming language we will use for our application. This depends on how well Bluetooth is supported/how easily we can set it up.

**Comment by bartekspitza** [comment]
Closing this issue.l Too much time has passed with nothing happening.
