### ISSUE TITLE
Configure Bluetooth connectivity between car and server

### ISSUE THREAD

**Issue by KalleHallden** [DIT112-V19/group-04#4]
As an operator I want to be able to send and receive data from the car via Bluetooth so that I can command and analyze it.

**Acceptance Criteria:**
Be able to send and receive short strings from a pc.

**Comment by konradotto** [comment]
Attempting connection using pybluez on Debian. So far no success.

**Comment by konradotto** [comment]
There seems to be an issue with our bluetooth-module. Transmitting data from the arduino to a python server works via bluetooth. Receiving has been unsuccessful. 
A connection using usb-to-serial has been created as a temporary fix until bluetooth connectivity can be provided. Testing a different bluetooth module is the next step and can only be attempted on Monday.

**Comment by platisd** [comment]
You can try this [app](https://play.google.com/store/apps/details?id=project.bluetoothterminal) to test if the connection is there (provided that your code and your connections are correct).
