### ISSUE TITLE
Connect a frontal ultrasound sensor

### ISSUE THREAD

**Issue by KalleHallden** [DIT112-V19/group-04#5]
As a safety advisor I want to be able to detect the distance to objects in front of the car in centimeters so that I can ensure the safety of the vehicle's collision avoidance.

**Acceptance Criteria:**
Be able to return distances between 1 cm and 100cm with an accuracy of 5 cm.

**Comment by konradotto** [comment]
The sensor is connected but the calibration for distance measurements still needs to be calibrated. Some sort of measurement device is required for this task.

**Comment by bartekspitza** [comment]
Closing this issue.
