### ISSUE TITLE
Set up Continuous Integration

### ISSUE THREAD

**Issue by platisd** [DIT112-V19/group-04#87]
## Description
**As** an open source developer considering to continue the project
**I would like to** know my contributions do not break the current system and I can always have the latest master release in an installable form
**so that** I can verify the system on my own hardware.

## Acceptance Criteria
* CI (preferably using [TravisCI](https://travis-ci.org)) is set up
* CI runs automatically for every new pull request
* At least two layers/components of the system are compiled succesfully on CI
* At least one layer/component of the system is released in an installable form (e.g. `.apk` for Android applications or `.hex` for Arduino sketches).

### Useful resources
* [DIT112-V19](https://github.com/DIT112-V19) groups with succesfully implemented CI
* [Publishing to Github releases from Travis CI](https://www.victorhurdugaci.com/github-releases-travis)
* [CI for an Arduino & Android repository](https://github.com/DIT112-V19/arduino-android-ci)

**Comment by platisd** [comment]
@WalrusArtist you still need to fix the deployment. The API key you have used doesn't seem to be working unfortunately.

**Comment by platisd** [comment]
@WalrusArtist you'll need to create a [personal access token](https://github.com/settings/tokens) with the `public_repo` permission. Copy that value and [encrypt it](https://docs.travis-ci.com/user/encryption-keys/#usage). After you've created your encrypted variable (e.g. `$GITHUB_TOKEN`) and included it in your Travis configuration file, use it instead of the value you have at the moment.

**Comment by WalrusArtist** [comment]
@platisd Should I create a new release again?

**Comment by platisd** [comment]
Yeap! Let's try it!

**Comment by platisd** [comment]
The credentials are still wrong. I suspect the problem can be solved if you follow the instructions below:
Run the `travis encrypt` command with the `--add` argument like this: `travis encrypt GITHUB_TOKEN="thesecretvalueyougotfromgithubandnotliterallythisstringlol" --add`

This will append some lines at the end of your `.travis.yml`. Then use `$GITHUB_TOKEN` in the `secure` field, e.g. `secure: $GITHUB_TOKEN`.

**Comment by platisd** [comment]
> @WalrusArtist you'll need to create a [personal access token](https://github.com/settings/tokens) with the `public_repo` permission. Copy that value and [encrypt it](https://docs.travis-ci.com/user/encryption-keys/#usage). After you've created your encrypted variable (e.g. `$GITHUB_TOKEN`) and included it in your Travis configuration file, use it instead of the value you have at the moment.

Please *carefully* follow the above instructions on how to create a **personal access token**. You have created a "deployment key" which I am not sure what it does. Create the *personal* token, encrypt it and name it `GITHUB_TOKEN`. Then update the secret encrypted value and it should work. I already did this in a fork of this repository.

**Comment by platisd** [comment]
Good job @WalrusArtist, it works now. :+1:
I hope through this exercise you got some better idea about CI, which is a domain always in demand across different technology domains. Good luck with the new academic year!
